[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "python adk_server_with_api.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
numReplicas = 1

[environments.production.variables]
OTEL_PYTHON_DISABLED = "true"
PORT = "8000"
RAILWAY_DEPLOYMENT_VERSION = "1.0.2"
# Note: Set GOOGLE_API_KEY and OPENWEATHER_API_KEY in Railway dashboard 